name: Docker Image CI

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
      - '.github/workflows/docker-image.yml'

  pull_request:
    branches: [ main ]
    
#concurrency:
#  group: workflow-${{ github.head_ref }}
#  cancel-in-progress: true

jobs:

  test:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
    
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y_%m_%d_%H_%M')"

#      - name: Public IP
#        id: ip
#        uses: haythem/public-ip@v1.2

#      - name: Print Public IP
#        run: |
#          echo "Public IPv4: ${{ steps.ip.outputs.ipv4 }}"
#          echo "Public IPv6: ${{ steps.ip.outputs.ipv6 }}"
          
      - name: Print platform ${{ matrix.platform }}
        run:  echo  ${{ matrix.platform }}
        
      - name: get all links from file
        run: cat Downloads.txt
        
      - name: download all links from file - Linux
        if: matrix.os == 'ubuntu-latest' 
        run: cat Downloads.txt | parallel --gnu "wget {}"
         
      - name: download all links from file - windows
        if: matrix.os == 'windows-latest'
        run: pwsh -command {cat Downloads.txt | foreach { Start-BitsTransfer $_ } }

        

