name: Docker Image CI

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
      - '.github/workflows/docker-image.yml'

  pull_request:
    branches: [ main ]
    
#concurrency:
#  group: workflow-${{ github.head_ref }}
#  cancel-in-progress: true

jobs: 
  windows: 
    runs-on: windows-latest
    steps:
    
    - uses: actions/checkout@v3
    
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y_%m_%d_%H_%M')"
    
    - name: get powershell version
      shell: pwsh
      run: $PSVersionTable
    
    #- name: get all pwsh modules
    #  shell: pwsh
    #  run: Get-Module -ListAvailable
      
    - name: get all pwsh modules
      shell: pwsh
      run: Invoke-RestMethod 'https://api.ipify.org?format=json'
    
    - name: get all pwsh modules
      shell: pwsh
      run: cat Downloads.txt | foreach { Start-BitsTransfer $_ }   
          

