name: Dvora 2 Go

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
      - '.github/workflows/docker-image.yml'

  pull_request:
    branches: [ main ]
    
#concurrency:
#  group: workflow-${{ github.head_ref }}
#  cancel-in-progress: true

jobs: 


  Linux:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v3
    
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y_%m_%d_%H_%M')"
    
    - name: Get Public IPv4
      shell: pwsh
      run: Invoke-RestMethod 'https://api.ipify.org?format=json'

    - name: Get local IPv4
      run: ip -br a
    
    - name: Create download folder
      run: mkdir DownloadFiles
      
    - name: Download all links from file
      run: |
        cd ./DownloadFiles
        cat ../Downloads.txt | parallel --gnu "wget {}"

    - name: Get all Files Hashes
      run: |
        cd ./DownloadFiles 
        sha256sum *
        #sha256sum * > all_hashes.txt
    
    - name: Get all Files Hashes
      shell: pwsh
      run: |
        Get-ChildItem ./DownloadFiles -File | Get-FileHash | Select -Property hash, @{N='File'; E={$_.path.split('/')[-1]}} | Export-Csv -Path ./DownloadFiles/linux_hash.csv -Encoding UTF8
        #Get-ChildItem ./DownloadFiles -File | Get-FileHash | Export-Csv -Path ./DownloadFiles/linux_hash.csv -Encoding UTF8
      
    - uses: actions/upload-artifact@v2
      with:
        name: linux-hash
        path: ./DownloadFiles/linux_hash.csv
    

  compare_hash:
    runs-on: ubuntu-latest
    needs: [Linux]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: linux-hash
      
      - name: get all files in current directory
        run: dir
        
      - name: import csv content
        shell: pwsh
        run: Import-Csv -Path linux_hash.csv | format-list
        
        
    
          

