name: test Dvora 2 Go

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
      - '.github/workflows/docker-image.yml'

  pull_request:
    branches: [ main ]

jobs: 

  Linux:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v3
    
    - id: googlesheet_actions
      uses: rjoydip/googlesheet-actions@0.1.1
      with:
        sheet-id: ${{ secrets.SHEET_ID }}
    - id: echo
      uses: actions/github-script@v2
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
            console.log(${{steps.googlesheet_actions.outputs.result}})
    - name: test
      run: |
        cat $HOME/data.json
    
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y_%m_%d_%H_%M')"
    
    - name: Get Public IPv4
      shell: pwsh
      run: Invoke-RestMethod 'https://api.ipify.org?format=json'

    - name: Get local IPv4
      run: ip -br a
    
    - name: Create download folder
      run: mkdir DownloadFiles
      
    - name: Download all links from file
      run: |
        cd ./DownloadFiles
        cat ../Downloads.txt | parallel --gnu "wget {}"

    - name: Get all Files Hashes
      run: |
        cd ./DownloadFiles 
        sha256sum *
